basePath: /
definitions:
  models.RegisterInput:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      role:
        type: string
      updated_at:
        type: string
    required:
    - email
    - name
    - password
    - role
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gin Swagger Example API
  version: "2.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /jobs/:
    get:
      consumes:
      - application/json
      description: Job details
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Job details
      tags:
      - jobs
    post:
      consumes:
      - application/json
      description: Update job as employee
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Update job
      tags:
      - jobs
  /jobs/:job_id/apply-job:
    post:
      consumes:
      - application/json
      description: Apply to the job
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Apply to the job
      tags:
      - jobs
      - employee
  /jobs/applied-jobs:
    get:
      consumes:
      - application/json
      description: Get all applied jobs for current logged in employee
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Get applied jobs
      tags:
      - jobs
      - employee
  /users/register:
    post:
      consumes:
      - application/json
      description: Register user.
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Register user.
      tags:
      - user
schemes:
- http
swagger: "2.0"
